language: python
dist: xenial
arch:
  - amd64
python:
  - 3.6
  - 3.7
  - 3.8
git:
  quiet: true
branches:
  only:
    - master
env:
  matrix:
    - LMOD_VERSION=7.8.2
    - LMOD_VERSION=8.2.10
    - LMOD_VERSION=8.3.5
addons:
  apt:
    packages:
      # install Lmod Deps
      - lua-filesystem
      - lua-json
      - lua-posix
      - lua-term
      - lua5.2
install:
  - pip --version
  - pip install --upgrade pip
  - pip --version
  - pip install coveralls
  - pip install -r docs/requirements.txt
  - source $TRAVIS_BUILD_DIR/scripts/install_lmod.sh $LMOD_VERSION

before_script:
  - type module
  - module --version

script:
  - sh $TRAVIS_BUILD_DIR/regtest.sh

after_success:
  - codecov
  - coveralls
